baseURL = "https://neildahiya.com/"
disqusShortname = "neildahiya"
languageCode = "en-us"
theme = "hugo-theme-console"
title = "neildahiya"
[params]
animateStyle = "animated pulse fast"
titleCutting = true
[[params.navlinks]]
name = "posts/"
url = "posts/"
[[params.navlinks]]
name = "book-reviews/"
url = "book-reviews/"
[[params.navlinks]]
name = "photos/"
url = "photos/"
[[params.navlinks]]
name = "lines/"
url = "lines/"
